# Generated by Django 5.2 on 2025-05-10 12:35

from django.db import migrations
from apps.generate import generate_user


def create_genders(apps, schema_editor):
    Gender = apps.get_model('staff', 'Gender')
    User = apps.get_model('staff', 'CustomUser')

    if Gender.objects.count() == 0:
        Gender.objects.create(value='M')
        Gender.objects.create(value='F')

    if User.objects.count() == 0:
        for _ in range(10):
            generate_user()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_genders, migrations.RunPython.noop),
    ]
