# Generated by Django 5.2 on 2025-05-14 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+7123456789'. Up to 15 digits allowed.", regex='^\\+?7?\\d[9,15]$')], verbose_name='phone number'),
        ),
    ]
