# Generated by Django 5.2 on 2025-05-04 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serve_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='serving date')),
                ('dish_name', models.CharField(verbose_name='dish name')),
                ('calories', models.PositiveIntegerField(verbose_name='calories')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.menuitem', verbose_name='dish')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu_items', to=settings.AUTH_USER_MODEL, verbose_name='guest')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='Clean', max_length=50, verbose_name='condition')),
                ('status', models.CharField(default='Available', max_length=50, verbose_name='status')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='checkin date')),
                ('checkout', models.DateField(verbose_name='checkout date')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='guest')),
                ('order_menu', models.ManyToManyField(related_name='bookings', to='deals.ordermenuitem', verbose_name='dishes')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.room')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
