# Generated by Django 5.2 on 2025-05-10 12:35

from django.db import migrations
from apps.generate import generate_room, generate_menu_item


def create_data(apps, schema_editor):
    Room = apps.get_model('deals', 'Room')
    MenuItem = apps.get_model('deals', 'MenuItem')

    if Room.objects.count() == 0:
        for _ in range(10):
            generate_room()

    if MenuItem.objects.count() == 0:
        for _ in range(10):
            generate_menu_item()


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_data_migration'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data, migrations.RunPython.noop),
    ]
