# Generated by Django 5.2 on 2025-05-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order_menu',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_order_menu_items', to='deals.ordermenuitem', verbose_name='order menu'),
        ),
    ]
